### PR TITLE
Transform mask data if orientation does not match volume, fixes #346

### LINKED ISSUE #346: Bug: Density calculation is wrong if orientation of volume and mask differs
Hi!

Huge fan of the work you did here, really makes these things much easier for someone without a huge medical background :)

I am currently testing the DRR-procedure with an open source CT-dataset and some segmentations masks generated using TotalSegmentator. During that, I ran into some unexpected behaviour. It turns out, that TotalSegmentator (at least in the version used by me) always saves the masks in LAS+ orientation, presumably because they want to make sure, that the orientation is always the same in the network and they don't bother to transform it back to the input data's orientation.

This screws over the density calculation in `read`, because `DiffDRR` never actually checks the orientation of the input arrays. In particular, this operation:
https://github.com/eigenvivek/DiffDRR/blob/30b59533992055c6c5dca9e5f8c9c1187ffba5b1/diffdrr/data.py#L141
only makes sense if the two arrays have the same orientation.

This only matters if one wants to create DRRs of individual bones/masked regions AND the orientation of the CT data and mask is not the same, but then it can be really annoying to debug, especially if you mask only the left/right bones and have a somewhat symmetrical field of view in the CT (ask me how I know...).

The easiest way to avoid those issues is probably to use `torchio`'s `ToCanonical()` everywhere, but if that is not acceptable for whatever reason, it can also be coded manually for the mask only.

### PR DESCRIPTION
**Pull request by LukasNickel**
Minimal addition to the code to fix the issue, that the volume and mask data have different orientations.

I avoided `ToCanonical` and instead only transform the mask data to match the volume.
After trying to implement the transform myself, I decided the safest way is probably to use the `nibabel` functionality directly. `Torchio` unfortunately only includes the transformation to canonical coordinates as far as I can tell...

Should be working fine, but I did not really test it much yet, which is why this is marked as draft. Hopefully I have the time for that on monday.

### CODE REVIEW

**Comment by eigenvivek** [comment]
Hi @LukasNickel thanks a bunch for the PR. Looks good to me!

To properly merge it, the changes have to be written into notebook (see the [dev guide](https://github.com/eigenvivek/DiffDRR/tree/main?tab=readme-ov-file#development)). If that's cumbersome, I can push those changes to this branch sometime soon.

**Comment by LukasNickel** [comment]
> Hi @LukasNickel thanks a bunch for the PR. Looks good to me!
> 
> To properly merge it, the changes have to be written into notebook (see the [dev guide](https://github.com/eigenvivek/DiffDRR/tree/main?tab=readme-ov-file#development)). If that's cumbersome, I can push those changes to this branch sometime soon.

I will have a look, just ran out of time on friday.

Although I have to admit, I initially misunderstood the purpose of the notebooks.
Would have assumed that the API doc is autogenerated from the code and the notebook content matters only for the "Tutorials"

**Comment by LukasNickel** [comment]
Turns out I completely skipped over the autogenerated comment in the code.
I was about to write how that might be a good idea to add lol.

There might still be a benefit of making the text in the README clearer, but I would say its 90% on me here and the description is mostly fine.
Just a niche thing to see literate programming in the wild and the autocorrect in my brain did not pick it up, mea culpa!

**Comment by eigenvivek** [comment]
Hi @LukasNickel thanks for the PR and the feedback. Looks good to me! I updated the README to be clearer.

**Comment by eigenvivek** [comment]
Closes #346

**Pull request merged**
